### ISSUE TITLE
Panic when running modified pointer analysis

### ISSUE THREAD

**Issue by zyq823** [o2lab/go2#10]
When executing code from branch "pta_replaced", an _invalid-memory-address_ panic was encountered. 

Sample output from running the test case cg.go (located at go2/race_checker/tests/) is shown below: 
```
INFO[10:15:15] Loading input packages...                    
INFO[10:15:16] command-line-arguments[/home/yiqingzhao94/Downloads/research/go2/race_checker/tests/cg.go] 
INFO[10:15:16] Done  -- packages loaded                     
INFO[10:15:16] Building SSA code for entire program...      
INFO[10:15:16] Done  -- SSA code built                      
 *** MODE: 1-ORIGIN-SENSITIVE *** 
INFO[10:15:16] Done -- PTA/CG Build; Using 103.899881ms. Go check gologfile for detail.  
Main CGNode: n3:cg177:command-line-arguments.main@[0:root call to command-line-arguments.main; ]

We are going to print out call graph. If not desired, turn off DEBUG.
#CGNode: 2435
n3:cg177:command-line-arguments.main@[0:root call to command-line-arguments.main; ]
  -> n4:cg5013:(*command-line-arguments.A).SetX@[0:go (*A).SetX(t0, 1:int)@command-line-arguments.main; ]
  -> n5:cg5018:fmt.Println@[0:shared contour; ]
  -> n6:cg5024:command-line-arguments.writeSlice@[0:root call to command-line-arguments.main; ]
  -> n5:cg5018:fmt.Println@[0:shared contour; ]
n6:cg5024:command-line-arguments.writeSlice@[0:root call to command-line-arguments.main; ]
n1:cg176:command-line-arguments.init@[0:shared contour; ]
  -> n2:cg5005:fmt.init@[0:shared contour; ]
n4:cg5013:(*command-line-arguments.A).SetX@[0:go (*A).SetX(t0, 1:int)@command-line-arguments.main; ]
  -> n5:cg5018:fmt.Println@[0:shared contour; ]

We are going to print out queries. If not desired, turn off DEBUG.
#Queries: 27  #Indirect Queries: 3  #Global Queries: 0
Queries Detail: 
n14809&[0:root call to command-line-arguments.main; ] (SSA:new A (a)): {[a]}
n14831&[0:root call to command-line-arguments.main; ] (SSA:&t10[0:int]): {[slicelit[*]]}
n25559&[0:go (*A).SetX(t0, 1:int)@command-line-arguments.main; ] (SSA:new [1]interface{} (varargs)): {[varargs]}
n14820&[0:root call to command-line-arguments.main; ] (SSA:&t5[0:int]): {[varargs[*]]}
n25575&[0:root call to command-line-arguments.main; ] (SSA:parameter s : []int): {[slicelit]}
n14813&[0:root call to command-line-arguments.main; ] (SSA:&t0.y [#1]): {[a.y]}
n14829&[0:root call to command-line-arguments.main; ] (SSA:new [4]int (slicelit)): {[slicelit]}
n14846&[0:root call to command-line-arguments.main; ] (SSA:make interface{} <- []int (t15)): {[makeinterface:[]int]}
n14848&[0:root call to command-line-arguments.main; ] (SSA:slice t17[:]): {[varargs]}
n14823&[0:root call to command-line-arguments.main; ] (SSA:make interface{} <- int (t4)): {[makeinterface:int]}
n14843&[0:root call to command-line-arguments.main; ] (SSA:&t17[0:int]): {[varargs[*]]}
n25552&[0:go (*A).SetX(t0, 1:int)@command-line-arguments.main; ] (SSA:parameter a : *A): {[a]}
n25566&[0:go (*A).SetX(t0, 1:int)@command-line-arguments.main; ] (SSA:slice t3[:]): {[varargs]}
n14833&[0:root call to command-line-arguments.main; ] (SSA:&t10[1:int]): {[slicelit[*]]}
n14835&[0:root call to command-line-arguments.main; ] (SSA:&t10[2:int]): {[slicelit[*]]}
n25554&[0:go (*A).SetX(t0, 1:int)@command-line-arguments.main; ] (SSA:&a.x [#0]): {[a.x]}
n25561&[0:go (*A).SetX(t0, 1:int)@command-line-arguments.main; ] (SSA:&t3[0:int]): {[varargs[*]]}
n14818&[0:root call to command-line-arguments.main; ] (SSA:new [1]interface{} (varargs)): {[varargs]}
n14841&[0:root call to command-line-arguments.main; ] (SSA:new [1]interface{} (varargs)): {[varargs]}
n25577&[0:root call to command-line-arguments.main; ] (SSA:&s[0:int]): {[slicelit[*]]}
n14811&[0:root call to command-line-arguments.main; ] (SSA:&t0.x [#0]): {[a.x]}
n14825&[0:root call to command-line-arguments.main; ] (SSA:slice t5[:]): {[varargs]}
n14837&[0:root call to command-line-arguments.main; ] (SSA:&t10[3:int]): {[slicelit[*]]}
n25564&[0:go (*A).SetX(t0, 1:int)@command-line-arguments.main; ] (SSA:make interface{} <- int (t2)): {[makeinterface:int]}
n14815&[0:root call to command-line-arguments.main; ] (SSA:&t0.x [#0]): {[a.x]}
n14839&[0:root call to command-line-arguments.main; ] (SSA:slice t10[:]): {[slicelit]}
n25556&[0:go (*A).SetX(t0, 1:int)@command-line-arguments.main; ] (SSA:&a.x [#0]): {[a.x]}

Indirect Queries Detail: 
n14844&[0:root call to command-line-arguments.main; ] (SSA:&t17[0:int]): {[makeinterface:[]int]}
n25562&[0:go (*A).SetX(t0, 1:int)@command-line-arguments.main; ] (SSA:&t3[0:int]): {[makeinterface:int]}
n14821&[0:root call to command-line-arguments.main; ] (SSA:&t5[0:int]): {[makeinterface:int]}

Global Queries Detail: 
INFO[10:15:16] Compiling stack trace for every Goroutine...  
 ****  Pointer Analysis did not record for this ssa.Value: *t3 **** 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x604734]

goroutine 1 [running]:
github.tamu.edu/April1989/go_tools/go/ssa.(*Go).String(...)
	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/ssa/print.go:294
github.tamu.edu/April1989/go_tools/go/pointer.(*ResultWCtx).PointsToByGo(0xc009373dc0, 0x7a7de0, 0xc006745800, 0x0, 0x7f8022c830f8, 0x47f785, 0x0)
	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/api.go:234 +0xd4
main.(*analysis).pointerAnalysis_new(0xc009366240, 0x7a7de0, 0xc006745800, 0x0, 0x7a7420, 0xc003e99cc0)
	/home/yiqingzhao94/Downloads/research/go2/race_checker/pointerAnalysis.go:115 +0xdf
main.(*analysis).pointerAnalysis(0xc009366240, 0x7a7de0, 0xc006745800, 0x0, 0x7a7420, 0xc003e99cc0)
	/home/yiqingzhao94/Downloads/research/go2/race_checker/pointerAnalysis.go:15 +0x65
main.(*analysis).insMakeInterface(0xc009366240, 0xc003e99cc0, 0x0, 0x7a7420, 0xc003e99cc0)
	/home/yiqingzhao94/Downloads/research/go2/race_checker/ssaInstructions.go:283 +0x1ac
main.(*analysis).visitAllInstructions(0xc009366240, 0xc0066fcb00, 0x0)
	/home/yiqingzhao94/Downloads/research/go2/race_checker/staticAnalysis.go:523 +0x2dbe
main.staticAnalysis(0xc00000c090, 0x1, 0x1, 0x1, 0x0)
	/home/yiqingzhao94/Downloads/research/go2/race_checker/staticAnalysis.go:170 +0xa8e
main.main()
	/home/yiqingzhao94/Downloads/research/go2/race_checker/main.go:173 +0x39f

```

**Comment by april1989** [comment]
I did not experience this on my workspace. My output shows 1 race: 
```
INFO[11:05:04] Compiling stack trace for every Goroutine...  
 ****  Pointer Analysis did not record for this ssa.Value: *t3 **** 
 ****  Pointer Analysis cannot match this ssa.Value: *t3 with main thread **** 
 ****  Pointer Analysis did not record for this ssa.Value: *t1 **** 
 ****  Pointer Analysis cannot match this ssa.Value: *t1 with this *ssa.GOgo (*A).SetX(t0, 1:int) **** 
INFO[11:05:04] Done  -- 2 goroutines analyzed! 32 instructions of interest detected!  
INFO[11:05:04] Building Happens-Before graph...             
INFO[11:05:04] Done  -- Happens-Before graph built          
INFO[11:05:04] Checking for data races...                   
INFO[11:05:04] Data race #1                                 
INFO[11:05:04] ==================================================================================================== 
INFO[11:05:04]  Read of &t0.x [#0] in function main at /Users/bozhen/Documents/GO2/go2/race_checker/tests/cg.go:20:16 
INFO[11:05:04]  in goroutine  ***  [ 0 ] ***                
INFO[11:05:04]  Write of &a.x [#0] in function SetX at /Users/bozhen/Documents/GO2/go2/race_checker/tests/cg.go:11:4 
INFO[11:05:04]  in goroutine  *** SetX [ 1 ] *** , with the following call stack:  
INFO[11:05:04]     --> Goroutine:  main [ 0 ]               
INFO[11:05:04] Locks acquired before Write access:  []      
INFO[11:05:04] Locks acquired before Read  access:  []      
INFO[11:05:04] ==================================================================================================== 
INFO[11:05:04] Done  --  1 race found!                      
Exiting.
```

I pushed all my code changes in "pta_replaced" (including modules), please check out the latest commit, see if any panic happens.

**Comment by zyq823** [comment]
Failing test cases are listed as follows:
```
Passed 52/58
--- FAIL: TestRace (92.80s)
    race_test.go:279: --- main: 2 source positions with expected (but not reported) races:
    race_test.go:282: Expected Race "Read":
          /home/yiqingzhao94/Downloads/research/go2/race_checker/tests/GoBench/Grpc/1748/main.go:66:6
    race_test.go:282: Expected Race "Write":
          /home/yiqingzhao94/Downloads/research/go2/race_checker/tests/GoBench/Grpc/1748/main.go:144:4
    race_test.go:279: --- main: 2 source positions with expected (but not reported) races:
    race_test.go:282: Expected Race "Write":
          /home/yiqingzhao94/Downloads/research/go2/race_checker/tests/GoBench/Istio/8144/main.go:16:4
    race_test.go:282: Expected Race "Read":
          /home/yiqingzhao94/Downloads/research/go2/race_checker/tests/GoBench/Istio/8144/main.go:55:8
    race_test.go:279: --- main: 2 source positions with expected (but not reported) races:
    race_test.go:282: Expected Race "Write":
          /home/yiqingzhao94/Downloads/research/go2/race_checker/tests/GoBench/Kubernetes/79631/main.go:14:11
    race_test.go:282: Expected Race "Read":
          /home/yiqingzhao94/Downloads/research/go2/race_checker/tests/GoBench/Kubernetes/79631/main.go:34:13
    race_test.go:279: --- main: 1 source positions with expected (but not reported) races:
    race_test.go:282: Expected Race "Read":
          /home/yiqingzhao94/Downloads/research/go2/race_checker/tests/GoBench/Kubernetes/81091/main.go:15:5
    race_test.go:282: Expected Race "Write":
          /home/yiqingzhao94/Downloads/research/go2/race_checker/tests/GoBench/Kubernetes/81091/main.go:15:5
    race_test.go:279: --- main: 2 source positions with expected (but not reported) races:
    race_test.go:282: Expected Race "Read":
          /home/yiqingzhao94/Downloads/research/go2/race_checker/tests/GoBench/Kubernetes/81148/main.go:51:13
    race_test.go:282: Expected Race "Write":
          /home/yiqingzhao94/Downloads/research/go2/race_checker/tests/GoBench/Kubernetes/81148/main.go:120:56
    race_test.go:279: --- main: 2 source positions with expected (but not reported) races:
    race_test.go:282: Expected Race "Write":
          /home/yiqingzhao94/Downloads/research/go2/race_checker/tests/GoBench/Kubernetes/88331/main.go:14:4
    race_test.go:282: Expected Race "Read":
          /home/yiqingzhao94/Downloads/research/go2/race_checker/tests/GoBench/Kubernetes/88331/main.go:33:20
```

**Comment by zyq823** [comment]
Panic when running "pta_replaced" on gRPC. Is there a way to bypass this internal panic? 
```
Internal panic in pointer analysis:
goroutine 1 [running]:
runtime/debug.Stack(0x24, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.tamu.edu/April1989/go_tools/go/pointer.AnalyzeWCtx.func1(0xc016da9560)
	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/analysis.go:409 +0x10b
panic(0x6d8ba0, 0xc013db1180)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.tamu.edu/April1989/go_tools/go/pointer.(*analysis).taggedValue(0xc009cf9860, 0xc0000c3a58, 0x1, 0x64, 0xc00ab46a80)
	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/gen.go:618 +0x105
github.tamu.edu/April1989/go_tools/go/pointer.(*untagConstraint).solve(0xc01bb28fa0, 0xc009cf9860, 0xc028c69d00)
	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/solve.go:296 +0xd0
github.tamu.edu/April1989/go_tools/go/pointer.(*analysis).solveConstraints(0xc009cf9860, 0xc024363440, 0xc028c69d00)
	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/solve.go:165 +0x166
github.tamu.edu/April1989/go_tools/go/pointer.(*analysis).solve(0xc009cf9860)
	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/solve.go:59 +0x19a
github.tamu.edu/April1989/go_tools/go/pointer.AnalyzeWCtx(0xc023013180, 0x0, 0x7a1340, 0xc013db11b0)
	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/analysis.go:543 +0x79c
main.staticAnalysis(0xc000098170, 0x0, 0x0, 0x2, 0x0)
	/home/yiqingzhao94/Downloads/research/go2/race_checker/staticAnalysis.go:161 +0x3bbf
main.main()
	/home/yiqingzhao94/Downloads/research/go2/race_checker/main.go:173 +0x39f
```

**Comment by april1989** [comment]
There are some missing invoke constraints for calls, working on the failing cases.

This internal panic (taggedValue), I need to take a look, to see the reason of this panic.

**Comment by april1989** [comment]
Fixed missing races in Kubernetes (79631, 81148, 88331) -> due to missing invoke constraints for repetitive static calls.

**Comment by april1989** [comment]
All missing races are fixed.

**Comment by zyq823** [comment]
Similar internal panic turns up again when running "pta_replaced" on TiDB. Is there a way to bypass this internal panic?

To test on TiDB: 
```
git clone https://github.com/pingcap/tidb.git
cd tidb/cmd/benchfilesort
go build
```
then by running race-checker with flags: `-useNewPTA -withoutComm -path=github.com/pingcap/tidb`
the internal panic looks like: 
```
Internal panic in pointer analysis:
goroutine 1 [running]:
runtime/debug.Stack(0x24, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.tamu.edu/April1989/go_tools/go/pointer.AnalyzeWCtx.func1(0xc00250f2d0)
	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/analysis.go:410 +0x10b
panic(0x6ed1a0, 0x92b160)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.tamu.edu/April1989/go_tools/go/pointer.(*callsite).loopEqual(0x0, 0xc0c82ecb10, 0xc00250e6e8)
	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/callgraph.go:152 +0x34
github.tamu.edu/April1989/go_tools/go/pointer.(*analysis).existClosure(0xc05075a5a0, 0xc07c5efb80, 0x0, 0x2, 0x32, 0xc00250e7d0, 0x6137c7, 0xc171fa1f80)
	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/gen.go:1413 +0x125
github.tamu.edu/April1989/go_tools/go/pointer.(*analysis).valueNodeClosure(0xc05075a5a0, 0xc060390060, 0xc07fe4b340, 0x7af080, 0xc07c5efb80, 0x0, 0x2, 0x29)
	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/gen.go:1360 +0x92
github.tamu.edu/April1989/go_tools/go/pointer.(*analysis).genInstr(0xc05075a5a0, 0xc060390060, 0x7af560, 0xc07fe4b340)
	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/gen.go:1745 +0xf06
github.tamu.edu/April1989/go_tools/go/pointer.(*analysis).genFunc(0xc05075a5a0, 0xc060390060)
	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/gen.go:2008 +0x6dc
github.tamu.edu/April1989/go_tools/go/pointer.(*analysis).generate(0xc05075a5a0)
	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/gen.go:2080 +0x1c5
github.tamu.edu/April1989/go_tools/go/pointer.AnalyzeWCtx(0xc099ca1500, 0x0, 0x7a7a40, 0xc171fa8360)
	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/analysis.go:509 +0x7f8
main.(*AnalysisRunner).Run(0xc00250ff60, 0xc0000100b0, 0x0, 0x0, 0x0, 0x0)
	/home/yiqingzhao94/Downloads/research/go2/race_checker/staticAnalysis.go:166 +0x468f
main.main()
	/home/yiqingzhao94/Downloads/research/go2/race_checker/main.go:181 +0x3f0
```

**Comment by april1989** [comment]
Some panics are due to my code, since I did not expect those behaviors during the existing benchmarks. Hence, I cannot remove those panics, instead, I need them to consider some special cases. If you see any, just report it here. I'll fix it to avoid similar panics. THX.

**Comment by april1989** [comment]
Fixed. 

> Similar internal panic turns up again when running "pta_replaced" on TiDB. Is there a way to bypass this internal panic?
> 
> To test on TiDB:
> 
> ```
> git clone https://github.com/pingcap/tidb.git
> cd tidb/cmd/benchfilesort
> go build
> ```
> 
> then by running race-checker with flags: `-useNewPTA -withoutComm -path=github.com/pingcap/tidb`
> the internal panic looks like:
> 
> ```
> Internal panic in pointer analysis:
> goroutine 1 [running]:
> runtime/debug.Stack(0x24, 0x0, 0x0)
> 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
> runtime/debug.PrintStack()
> 	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
> github.tamu.edu/April1989/go_tools/go/pointer.AnalyzeWCtx.func1(0xc00250f2d0)
> 	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/analysis.go:410 +0x10b
> panic(0x6ed1a0, 0x92b160)
> 	/usr/local/go/src/runtime/panic.go:969 +0x175
> github.tamu.edu/April1989/go_tools/go/pointer.(*callsite).loopEqual(0x0, 0xc0c82ecb10, 0xc00250e6e8)
> 	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/callgraph.go:152 +0x34
> github.tamu.edu/April1989/go_tools/go/pointer.(*analysis).existClosure(0xc05075a5a0, 0xc07c5efb80, 0x0, 0x2, 0x32, 0xc00250e7d0, 0x6137c7, 0xc171fa1f80)
> 	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/gen.go:1413 +0x125
> github.tamu.edu/April1989/go_tools/go/pointer.(*analysis).valueNodeClosure(0xc05075a5a0, 0xc060390060, 0xc07fe4b340, 0x7af080, 0xc07c5efb80, 0x0, 0x2, 0x29)
> 	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/gen.go:1360 +0x92
> github.tamu.edu/April1989/go_tools/go/pointer.(*analysis).genInstr(0xc05075a5a0, 0xc060390060, 0x7af560, 0xc07fe4b340)
> 	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/gen.go:1745 +0xf06
> github.tamu.edu/April1989/go_tools/go/pointer.(*analysis).genFunc(0xc05075a5a0, 0xc060390060)
> 	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/gen.go:2008 +0x6dc
> github.tamu.edu/April1989/go_tools/go/pointer.(*analysis).generate(0xc05075a5a0)
> 	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/gen.go:2080 +0x1c5
> github.tamu.edu/April1989/go_tools/go/pointer.AnalyzeWCtx(0xc099ca1500, 0x0, 0x7a7a40, 0xc171fa8360)
> 	/home/yiqingzhao94/Downloads/research/go2/go_pointeranlaysis/go/pointer/analysis.go:509 +0x7f8
> main.(*AnalysisRunner).Run(0xc00250ff60, 0xc0000100b0, 0x0, 0x0, 0x0, 0x0)
> 	/home/yiqingzhao94/Downloads/research/go2/race_checker/staticAnalysis.go:166 +0x468f
> main.main()
> 	/home/yiqingzhao94/Downloads/research/go2/race_checker/main.go:181 +0x3f0
> ```

**Comment by zyq823** [comment]
> Some panics are due to my code, since I did not expect those behaviors during the existing benchmarks. Hence, I cannot remove those panics, instead, I need them to consider some special cases. If you see any, just report it here. I'll fix it to avoid similar panics. THX.

When running on opencontainers/runc, previously reported internal panic seems now to be ignored, but callee information is still not collected. Specifically when looking at main() in main.go, instructions within
`app.Flags = []cli.Flag{...}` (line 82) 
and 
`app.Commands = []cli.Command{...}` (line 117, this one contains *ssa.UnOp instructions of interest)
are not considered in pta_replaced branch. 

To test on opencontainers/runc:
```
git clone https://github.com/opencontainers/runc.git
cd runc
go build
```
then run `race-checker` with flags `-useNewPTA -withoutComm -path=github.com/opencontainers/runc`
